"""empty message

Revision ID: 027d437c7e9a
Revises: bcc444c17db8
Create Date: 2023-01-21 19:23:38.162226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027d437c7e9a'
down_revision = 'bcc444c17db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('species', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
