"""empty message

Revision ID: 60eeaad9f9eb
Revises: 6f0982ee1d38
Create Date: 2023-01-22 14:51:49.348333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60eeaad9f9eb'
down_revision = '6f0982ee1d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('is_alive',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('is_alive',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
