"""empty message

Revision ID: 6f0982ee1d38
Revises: 027d437c7e9a
Create Date: 2023-01-22 14:35:37.457203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0982ee1d38'
down_revision = '027d437c7e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_alive', sa.Boolean(), nullable=True))
        batch_op.drop_column('alive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alive', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_alive')

    # ### end Alembic commands ###
