"""empty message

Revision ID: bcc444c17db8
Revises: b2ecbc401e73
Create Date: 2023-01-21 19:23:00.416779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc444c17db8'
down_revision = 'b2ecbc401e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('species', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('name', name='character_name_key')
    )
    # ### end Alembic commands ###
